-- eliminar si existe la base de datos
DROP DATABASE IF EXISTS DBSEXTO2025;
-- crear la base de datos 
CREATE DATABASE DBSEXTO2025;
-- activar la base de datos a usar
USE DBSEXTO2025; 
-- Eliminar la tabla si existe
DROP TABLE IF EXISTS PERMISO;
-- crear la tabla de permiso
CREATE TABLE PERMISO(
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	NOMBRE VARCHAR(50)  NOT NULL
)ENGINE=InnoDB;

-- Eliminar la tabla usuario si existe
DROP	TABLE IF EXISTS USUARIO;
-- Crar la tabla usuario
CREATE TABLE USUARIO(
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	NOMBRE VARCHAR(100) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL,
	PASSWORD VARCHAR(250) NOT NULL,
	TELEFONO VARCHAR(15),
	IDPERMISO INT NOT NULL,
	FOREIGN KEY (IDPERMISO) REFERENCES PERMISO(ID)
)ENGINE=InnoDB;

-- Adicionar datos a la tabla permiso
INSERT INTO PERMISO(NOMBRE)
VALUES('Admin');
INSERT INTO PERMISO(NOMBRE)
VALUES('Vendedor');
INSERT INTO PERMISO(NOMBRE)
VALUES('Cliente');
INSERT INTO PERMISO(NOMBRE)
VALUES('Propietario');
INSERT INTO PERMISO(NOMBRE)
VALUES('Invitado'); 

-- realizar la consulta de la tabla permiso
SELECT * FROM PERMISO;
-- adicionar datos a la tabla usuario
INSERT INTO USUARIO(NOMBRE,EMAIL,PASSWORD,TELEFONO,IDPERMISO)
VALUES('Marcos','marcos@gmail.com','123456','7215555',2);

SELECT * FROM USUARIO;
SELECT * FROM PERMISO;
 